// <auto-generated>
// This file is generated from the Generic Sound Collection in Resources.
// Any changes will be overwritten by the editor updater.
// </auto-generated>

namespace Services
{
	public static partial class DJ
	{
		public static IDesignSound Click_Sound => GenericCollection != null ? GenericCollection.Get("Click") : null;
		public static IDesignSound ClickOn_Sound => GenericCollection != null ? GenericCollection.Get("ClickOn") : null;
		public static IDesignSound ClickOff_Sound => GenericCollection != null ? GenericCollection.Get("ClickOff") : null;
		public static IDesignSound SelectOff_Sound => GenericCollection != null ? GenericCollection.Get("SelectOff") : null;
		public static IDesignSound SelectOn_Sound => GenericCollection != null ? GenericCollection.Get("SelectOn") : null;
	}
}
