// <auto-generated>
// This file is generated from the Generic Sound Collection in Resources.
// Any changes will be overwritten by the editor updater.
// </auto-generated>

namespace Services
{
	public static partial class DJ
	{
		public static IDesignSound Click_Sound => GenericCollection != null ? GenericCollection.Get("Click") : null;
		public static IDesignSound Play_Sound => GenericCollection != null ? GenericCollection.Get("Play") : null;
	}
}
